<a href="https://colab.research.google.com/github/Larr014/DataMining/blob/master/Ejemplo_Regresion_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importamos pandas, libreria para uso de dataframe

In [1]:
import pandas as pd

Utilizamos pandas para leer un archivo csv

In [3]:
df = pd.read_csv("/content/socioeconimico.csv")
df

Edad  Ingresos    Educacion  Experiencia  Gastos
0     23     50000  Universidad            2   15000
1     26     55000   Secundaria            4   10000
2     30     60000  Universidad            6   20000
3     35     75000        Grado            8   25000
4     40     80000        Grado           10   30000
..   ...       ...          ...          ...     ...
63    58     98000  Universidad           18   45000
64    44     84000   Secundaria           13   31000
65    49     89000  Universidad           15   36000
66    54     94000        Grado           17   41000
67    59     99000        Grado           19   46000

[68 rows x 5 columns]

In [ ]:
df.describe()

Edad       Ingresos  Experiencia        Gastos
count  68.000000      68.000000    68.000000     68.000000
mean   47.308824   86602.941176    12.808824  34088.235294
std    11.402091   15679.761369     4.770110  11774.923131
min    23.000000   50000.000000     2.000000  10000.000000
25%    39.000000   79000.000000     9.750000  26750.000000
50%    47.500000   87500.000000    13.000000  35000.000000
75%    56.000000   96000.000000    17.000000  43250.000000
max    69.000000  119000.000000    21.000000  55000.000000

In [ ]:
df

Edad  Ingresos    Educacion  Experiencia  Gastos
0     23     50000  Universidad            2   15000
1     26     55000   Secundaria            4   10000
2     30     60000  Universidad            6   20000
3     35     75000        Grado            8   25000
4     40     80000        Grado           10   30000
..   ...       ...          ...          ...     ...
63    58     98000  Universidad           18   45000
64    44     84000   Secundaria           13   31000
65    49     89000  Universidad           15   36000
66    54     94000        Grado           17   41000
67    59     99000        Grado           19   46000

[68 rows x 5 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['Edad'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['Ingresos'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['Experiencia'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df, *['Gastos'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['Edad'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['Ingresos'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['Experiencia'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df, *['Gastos'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(df, *['Educacion'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(df, *[[['Edad', 'Ingresos'], ['Ingresos', 'Experiencia'], ['Experiencia', 'Gastos']]], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['Edad', 'Educacion'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['Ingresos', 'Educacion'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['Experiencia', 'Educacion'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(df, *['Gastos', 'Educacion'], **{'inner': 'stick'})
chart

In [5]:
df["Ingresos"] #Muestra solo la columna Ingresos

0     50000
1     55000
2     60000
3     75000
4     80000
      ...  
63    98000
64    84000
65    89000
66    94000
67    99000
Name: Ingresos, Length: 68, dtype: int64

In [ ]:
df["Edad"] #Muestra solo la columna edad

0     23
1     26
2     30
3     35
4     40
      ..
63    58
64    44
65    49
66    54
67    59
Name: Edad, Length: 68, dtype: int64

In [8]:
df["Edad"].values #Muestra la columna edad pero ya no como dataframe

array([23, 26, 30, 35, 40, 45, 50, 55, 60, 64, 27, 31, 36, 41, 46, 51, 56,
       61, 65, 28, 32, 37, 42, 47, 52, 57, 62, 66, 29, 33, 38, 43, 48, 53,
       58, 63, 67, 34, 39, 44, 49, 54, 59, 68, 37, 40, 45, 50, 55, 69, 38,
       41, 46, 51, 56, 39, 42, 47, 52, 57, 43, 48, 53, 58, 44, 49, 54, 59])

In [9]:
df["Edad"].values.reshape(-1,1) #Cambia la dimension de lo anterior

array([[23],
       [26],
       [30],
       [35],
       [40],
       [45],
       [50],
       [55],
       [60],
       [64],
       [27],
       [31],
       [36],
       [41],
       [46],
       [51],
       [56],
       [61],
       [65],
       [28],
       [32],
       [37],
       [42],
       [47],
       [52],
       [57],
       [62],
       [66],
       [29],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63],
       [67],
       [34],
       [39],
       [44],
       [49],
       [54],
       [59],
       [68],
       [37],
       [40],
       [45],
       [50],
       [55],
       [69],
       [38],
       [41],
       [46],
       [51],
       [56],
       [39],
       [42],
       [47],
       [52],
       [57],
       [43],
       [48],
       [53],
       [58],
       [44],
       [49],
       [54],
       [59]])

Aplicamos lo mencionado arriba a cada columna de interes

In [13]:
x = df["Edad"].values.reshape(-1,1)
y1 = df["Ingresos"].values.reshape(-1,1)
y2 = df["Gastos"].values.reshape(-1,1)

In [10]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [11]:
import numpy as np

Definir un modelo -
Ajustar el modelo

In [14]:
reg1 = linear_model.LinearRegression()
reg1.fit(x,y1)

LinearRegression()

Permite predecir cuanto deberia recibir de ingreso una persona que tiene 30 y otra de 14

In [15]:
salida = reg1.predict([[30],[14]])
salida

array([[63186.06653554],
       [41539.88165081]])

Creamos otro modelo, pero lo ajustamos ahora a la edad y los ingresos al mismo tiempo

In [16]:
reg2 = linear_model.LinearRegression()
reg2.fit(df.loc[:,["Edad","Ingresos"]].values,y2)
salida = reg2.predict([[30,63186]]) #Veamos que gasto deberia tener una persona que tiene 30 y recibe de ingresos 63186
salida

array([[17179.545258]])

Separamos el conjunto de datos, cambiar el test_size segun porcentaje que deseas que tenga el conjunto de prueba

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, df['Gastos'],
                                                    test_size=0.05, random_state=42
                                                    )

In [31]:
reg3 = linear_model.LinearRegression()
reg3.fit(X_train.loc[:,["Edad","Ingresos"]].values,y_train) #El ajuste se realiza solo con el 80% del conjunto de la fase anterior (train)
salidas = reg3.predict(X_test.loc[:,["Edad","Ingresos"]].values) #Probemos el modelo con el 20% del conjunto de la fase anterior (test)

In [25]:
from sklearn.metrics import max_error

In [ ]:
6197,4593

(14,)

In [32]:
error = max_error(y_test,salidas)
error

5221.436581824193